using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Flight_Management_System.Models
{
    public class Flight
    {
        public int flightId { get; set; } //syste generated Unique identifier for each scheduled flight 
        public string flightCode { get; set; } //Airline flight code (e.g. OA-201) — generated by system
        public int aircraftId { get; set; }// ID of the aircraft assigned to this flight
        public int pilotId { get; set; }// ID of the pilot assigned to this flight
        public string origin { get; set; }// Departure airport / city
        public string destination { get; set; }// Arrival airport / city 
        public string departureDate { get; set; } // Scheduled departure date 
        public string departureTime { get; set; } // Scheduled departure time
        public int flightDuration { get; set; } // calculated from pilot flight houers
        public decimal ticketPrice { get; set; }// Price per seat for this flight
        public int availableSeats { get; set; }//Number of seats still open for booking — decrements on booking
        public string status { get; set; }// Flight status: Scheduled | Departed | Cancelled
    }
}
